Class components
mamont79/rss-react-2024 pull request #1
Opened 2024-07-03 17:56 UTC by mamont79

1. Task: (link)[https://github.com/rolling-scopes-school/tasks/blob/master/react/modules/tasks/class-components.md]
2. Screenshot:
   will be soon
3. Deployment: not required
4. Done 05.07.2024 / deadline 08.07.2024
5. Score: 100 / 100
  - [x] Eslint is set up, when lint command is run it doesn't produce any errors - 15 points
  - [x] Prettier is set up, format:fix command fixes issues - 15 points
  - [x] Husky is set up, linting is run on pre-commit - 10 points
  - [x] Page is split into 2 sections, 
  - [ ] When user types something to the Search input and clicks "Search" button, a loader is displayed and the list is changed according to the response results for a provided search term - 15 points 
  - [ ] The search term typed into the Search input is saved in the LS
  - [x] Application is wrapped with ErrorBoundary, which logs error to a console and shows a fallback UI. There should be a button to throw an error - 10 points

2024-07-05 10:06 UTC, AnnaIgnatova requested changes

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/App.css
> +@keyframes logo-spin {
этот код точно нужен?

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/api/getOnePokemon.ts
> +const geOnePokemon = async (id: number | string) => {
опечатка get*

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/api/index.ts
> +import axios from 'axios';
лучше по-другому организовать файлы в папке, инстанс вынести в отдельный файл, в index импортировать все функции из апи

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/api/index.ts
> +  baseURL: 'https://pokeapi.co/api/v2/pokemon/',
лучше вынести в константу

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/components/card/index.tsx
> +        <p className="pokemon-name">{this.props.pokemonsCard.name}</p>
а мы всегда получаем pokemonsCard?

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/components/display/index.tsx
> +export class Display extends React.Component {
не совсем понятно что за компонент из названия

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/components/display/index.tsx
> +    const savedSearchPokemon = localStorage.getItem('searchPokemon');
название ключа вынести в константу

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/components/display/index.tsx
> +              key={Number(el.url.split('/').reverse()[1])}
тут key можно убрать

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/components/display/index.tsx
> +          url: `https://pokeapi.co/api/v2/pokemon/${data.id}/`,
а зачем тебе здесь url апишки

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/components/header/buttonMistake.tsx
> +interface ButtonProps {}
пустой интерфейс

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/components/header/index.tsx
> +interface HeaderProps {}
пустой интерфейс

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/components/header/index.tsx
> +interface HeaderProps {}
кстати почему где то пропсы описаны через тип, а где то через интерфейс, надо прийти к чему то одному

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/components/header/index.tsx
> +    const savedSearchPokemon = localStorage.getItem('searchPokemon');
ключ в константу

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/components/header/index.tsx
> +        <div className="searh-wrapper">
search

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/components/header/style.css
> +.searchInput {
нужно выбрать один стиль именования классов, или через - или camelCase

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/errorBoundary/style.css
> +.mistake {
думаю тут нужно поменять название, так как оно не отражает сути
возможно тут подойдет error-content

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/pages/mainPage/index.tsx
> +
пустая строчка

2024-07-05 10:06 UTC, AnnaIgnatova commented on rs-react/src/types/types.ts
> +export type PokemonUrlData = {
разбить в папке types типы по папкам, а то пока здесь все подряд

2024-07-05 11:10 UTC, AnnaIgnatova commented on rs-react/src/components/card/index.tsx
> +          <div className="loader">
лоадер лучше вынести в отдельный компонент

2024-07-05 13:01 UTC, mamont79 commented on rs-react/src/components/header/style.css
> +.searchInput {
да, это немного затупил... в планах было поменять.... опередила меня)))

2024-07-05 13:02 UTC, mamont79 commented on rs-react/src/components/header/index.tsx
> +        <div className="searh-wrapper">
нельзя с температурой кодить.... лезут опечатки)))

2024-07-05 13:06 UTC, mamont79 commented on rs-react/src/api/index.ts
> +import axios from 'axios';
не совсем понял что ты имеешь ввиду

2024-07-05 13:10 UTC, mamont79 commented on rs-react/src/components/card/index.tsx
> +        <p className="pokemon-name">{this.props.pokemonsCard.name}</p>
да

2024-07-05 13:44 UTC, mamont79 commented on rs-react/src/types/types.ts
> +export type PokemonUrlData = {
постараюсь добраться и разгрести всё это)))

2024-07-08 13:52 UTC, AnnaIgnatova commented on rs-react/src/api/index.ts
> +import axios from 'axios';
я про то, что нужно создать для инстанса отдельный файл
а в файле index экспортировать все функции из папки апи, чтоб потом импорт у тебя был как ниже

import {getPokemons} from '..***../api'

2024-11-21 12:48 UTC, merged